### ISSUE TITLE
Unbalanced validation set data

### ISSUE THREAD

**Issue by jiaweiguan** [jozhang97/MutateEverything#2]
When I was observing the dataset, I found that cdna test dataset is all double mutation.  Is there a test dataset for single mutation?

**Comment by jozhang97** [comment]
Right, we test on the cdna double mutations and single mutations separately.

We do have a cDNA test set for single mutations but did not prioritize it in this work... is it something of interest?

**Comment by jiaweiguan** [comment]
In my understanding, this test dataset is used for model selection and evaluation. To have a more comprehensive evaluation and ensure good performance on the actual test set, s669, it is important to have this specific dataset with single mutations. If you could provide this portion of the dataset, I would be extremely grateful. Your work is excellent, and I hope to engage in more discussions and collaborations on GitHub in the future.

**Comment by jozhang97** [comment]
Thanks for your interest. I added this test set to the other datasets.

You can find it at https://drive.google.com/drive/folders/1psp5LBnAWpwkzGtsWD9SJgauo8xX_eaK?usp=sharing

**Comment by jiaweiguan** [comment]
Wow, thank you for your help.
