### ISSUE TITLE
Mismatch of AlphaFold Test Results

### ISSUE THREAD

**Issue by ChrisAllenMing** [jozhang97/MutateEverything#5]
Hi authors, thanks for the great work! 

When I try to reproduce the test demo results of AlphaFold-based model with [the provided command](https://github.com/jozhang97/MutateEverything#evaluation), I meet mismatch between [the results on my side](https://drive.google.com/drive/folders/1A-fVZx-nGdTdIJ8WVbOZ0ryWPFSPnIZy?usp=sharing) and [the results in this repo](https://github.com/jozhang97/MutateEverything/tree/master/example/1gl5_af). Cound you kindly suggest the possible reason? I follow your instruction to set up the environment on a A100 server with CUDA-11.4. You can download my results to see the clear difference, and here are some intuitive comparisons:

My single mutation predictions:
<img width="917" alt="single_mutate_ours" src="https://github.com/jozhang97/MutateEverything/assets/26819805/16343836-bca7-4212-adc2-a5079421e2e4">

Single mutation predictions in this repo:
<img width="916" alt="single_mutate_official" src="https://github.com/jozhang97/MutateEverything/assets/26819805/9a82b91c-f063-462c-a5b4-3938f3aab8e1">

**Comment by jozhang97** [comment]
Hi Alan,

Thanks for your interest and sorry you have been having troubles.

Could you run the ESM model and see if the results match with that backbone? This would help us determine if the issue lies with openfold or elsewhere.

Thanks!

**Comment by ChrisAllenMing** [comment]
Hi Jeffrey,

Thanks for your response. I have confirmed that the test results of ESM model on my end match with yours.

Best,
Minghao

**Comment by jozhang97** [comment]
Hi,

That's great.

I suspect that there is difference in the OpenFold installation related to torch/cuda versioning. Beyond that, it's not immediately clear to me what's going on.
We use torch1.12.1+cuda11.3 and use the `b5fa2ba` commit on openfold. Do you do the same?

**Comment by ChrisAllenMing** [comment]
Hi Jeffrey,

Thanks for the rapid response.

By using the same environment with "torch1.12.1 + cuda11.3 + the b5fa2ba commit on openfold", I still cannot get your AlphaFold model results on the test case. Actually, my test result is still the same as in the first question. Here is my single mutation result:

<img width="917" alt="single_mutate_ours" src="https://github.com/jozhang97/MutateEverything/assets/26819805/96bc71cf-f8ad-4bae-9222-b890e5c50565">

**Comment by jozhang97** [comment]
Hi Minghao,

Sorry for the inconvenience. Could you see if the performance on the S669 test set is the same? If so, the model should be properly loaded.

You can download S669 from https://drive.google.com/drive/u/1/folders/1psp5LBnAWpwkzGtsWD9SJgauo8xX_eaK
The following eval command should work, replacing `/path/to/mutate_everything_af.pth` with your model path.

```
torchrun --nproc_per_node=3 main_train.py \
    --batch_size 1 \
    --data_path data/cdna/mutations/cdna_train.csv \
    --eval_data_paths data/s669/mutations/s669.csv \
    --dist_eval \
    --backbone esm2_t33_650M_UR50D \
    --freeze_at 14 \
    --lambda_double 0. --lambda_single 1. \
    --eval_period 999 --epochs 20 --warmup_epochs 2 --save_period 20 \
    --disable_wandb \
    --output_dir logs/esm_single \
    --resume /path/to/mutate_everything_af.pth --eval
```

**Comment by ChrisAllenMing** [comment]
Hi Jeffrey,

As you suggested, I run an evaluation on the S669 dataset. Here are the results which roughly align with the results in the paper:

<img width="866" alt="s669_results" src="https://github.com/jozhang97/MutateEverything/assets/26819805/4e9e037f-88d2-417c-b157-6ad2845045b5">

Could this suggest that my local setup mostly aligns with yours?

**Comment by jozhang97** [comment]
Yea, the local setup looks right.

Thanks for catching this, I need to look into that original example more carefully.

**Comment by ChrisAllenMing** [comment]
Thanks again for your help during this process.

I will close this issue for now.

**Comment by ChrisAllenMing** [comment]
Thanks again for your help during this process.

I will close this issue for now.
